ERROR:__main__:'module' object is not callable
Traceback (most recent call last):
  File "D:\Github Push Folder\Bank App\main.py", line 23, in start_up
    last_name = user(first_name, last_name, password, amount)
TypeError: 'module' object is not callable
ERROR:__main__:'user' object has no attribute 'fullname'
Traceback (most recent call last):
  File "D:\Github Push Folder\Bank App\main.py", line 25, in start_up
    f'Created Employee: {last_name.fullname} - {last_name.user_id}')
AttributeError: 'user' object has no attribute 'fullname'
INFO:__main__:Created Employee: AkhshyGanesh - Akhshy1
INFO:__main__:Created Employee: AkhshyGanesh - Akhshy1
INFO:__main__:Created Employee: akhshyganeshb - akhshyganesh1
ERROR:__main__:
MySQL Connection not available.
Traceback (most recent call last):
  File "D:\Github Push Folder\Bank App\main.py", line 27, in start_up
    database_operation.insert_user()
  File "D:\Github Push Folder\Bank App\database_operation.py", line 27, in insert_user
    with connection.cursor() as cursor:
  File "D:\Github Push Folder\Bank App\BankAppVenv\lib\site-packages\mysql\connector\connection.py", line 1016, in cursor
    raise errors.OperationalError("MySQL Connection not available.")
mysql.connector.errors.OperationalError: MySQL Connection not available.
ERROR:__main__:
MySQL Connection not available.
Traceback (most recent call last):
  File "D:\Github Push Folder\Bank App\main.py", line 27, in start_up
    database_operation.insert_user()
  File "D:\Github Push Folder\Bank App\database_operation.py", line 26, in insert_user
    with connection.cursor() as cursor:
  File "D:\Github Push Folder\Bank App\BankAppVenv\lib\site-packages\mysql\connector\connection.py", line 1016, in cursor
    raise errors.OperationalError("MySQL Connection not available.")
mysql.connector.errors.OperationalError: MySQL Connection not available.
ERROR:__main__:
MySQL Connection not available.
Traceback (most recent call last):
  File "D:\Github Push Folder\Bank App\main.py", line 27, in start_up
    database_operation.insert_user()
  File "D:\Github Push Folder\Bank App\database_operation.py", line 23, in insert_user
    with connection.cursor() as cursor:
  File "D:\Github Push Folder\Bank App\BankAppVenv\lib\site-packages\mysql\connector\connection.py", line 1016, in cursor
    raise errors.OperationalError("MySQL Connection not available.")
mysql.connector.errors.OperationalError: MySQL Connection not available.
ERROR:__main__:
invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "D:\Github Push Folder\Bank App\main.py", line 19, in start_up
    account = int(input('ALREADY USER OR SIGN UP (1/2): '))
ValueError: invalid literal for int() with base 10: ''
ERROR:__main__:
'tuple' object has no attribute 'append'
Traceback (most recent call last):
  File "D:\Github Push Folder\Bank App\main.py", line 35, in start_up
    user = database_operation.get_user_detail(user_name)
  File "D:\Github Push Folder\Bank App\database_operation.py", line 57, in get_user_detail
    user.append(row)
AttributeError: 'tuple' object has no attribute 'append'
ERROR:__main__:
can only concatenate str (not "int") to str
Traceback (most recent call last):
  File "D:\Github Push Folder\Bank App\main.py", line 39, in start_up
    database_operation.deposit_amount(user_obj.user_id(), amount)
  File "D:\Github Push Folder\Bank App\database_operation.py", line 89, in deposit_amount
    amount += user[0]
TypeError: can only concatenate str (not "int") to str
ERROR:__main__:
can only concatenate str (not "int") to str
Traceback (most recent call last):
  File "D:\Github Push Folder\Bank App\main.py", line 39, in start_up
    database_operation.deposit_amount(user_obj.user_id(), amount)
  File "D:\Github Push Folder\Bank App\database_operation.py", line 90, in deposit_amount
    amount += user[0]
TypeError: can only concatenate str (not "int") to str
ERROR:__main__:
can only concatenate str (not "int") to str
Traceback (most recent call last):
  File "D:\Github Push Folder\Bank App\main.py", line 39, in start_up
    database_operation.deposit_amount(user_obj.user_id(), amount)
  File "D:\Github Push Folder\Bank App\database_operation.py", line 90, in deposit_amount
    amount += user[0]
TypeError: can only concatenate str (not "int") to str
ERROR:__main__:
'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "D:\Github Push Folder\Bank App\main.py", line 54, in start_up
    print('Found the user_name: ', user[0])
TypeError: 'NoneType' object is not subscriptable
ERROR:__main__:
'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "D:\Github Push Folder\Bank App\main.py", line 49, in start_up
    print('Found the user_name: ', user[0])
TypeError: 'NoneType' object is not subscriptable
ERROR:__main__:
'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "D:\Github Push Folder\Bank App\main.py", line 51, in start_up
    print('Found the user_name: ', user[0])
TypeError: 'NoneType' object is not subscriptable
ERROR:__main__:
'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "D:\Github Push Folder\Bank App\main.py", line 51, in start_up
    print('Found the user_name: ', user[0])
TypeError: 'NoneType' object is not subscriptable
ERROR:__main__:
'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "D:\Github Push Folder\Bank App\main.py", line 51, in start_up
    print('Found the user_name: ', user[0])
TypeError: 'NoneType' object is not subscriptable
ERROR:__main__:
unsupported operand type(s) for +=: 'int' and 'str'
Traceback (most recent call last):
  File "D:\Github Push Folder\Bank App\main.py", line 56, in start_up
    database_operation.deposit_amount(user_name, amount)
  File "D:\Github Push Folder\Bank App\database_operation.py", line 103, in deposit_amount
    amount += str(current_amount)
TypeError: unsupported operand type(s) for +=: 'int' and 'str'
ERROR:__main__:
unsupported operand type(s) for +=: 'int' and 'str'
Traceback (most recent call last):
  File "D:\Github Push Folder\Bank App\main.py", line 56, in start_up
    database_operation.deposit_amount(user_name, amount)
  File "D:\Github Push Folder\Bank App\database_operation.py", line 103, in deposit_amount
    amount += str(current_amount)
TypeError: unsupported operand type(s) for +=: 'int' and 'str'
